spring.application.name=Secure Enrollment Service
spring.application.version=0.0.3

server.port=8443
server.compression.enabled=true
server.compression.mime-types=application/octet-stream
server.compression.min-response-size=1024