spring.application.name=Secure Enrollment Service
spring.application.version=0.0.3

# Server settings
server.port=8443
server.compression.enabled=true
server.compression.mime-types=application/octet-stream
server.compression.min-response-size=1024

# H2 Database URL
# spring.datasource.url=jdbc:h2:file:./src/main/resources/data/testdb
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=runH2N0w

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update