# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: enrollmentProto.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'enrollmentProto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65nrollmentProto.proto\x12\x1aonline.eracodes.enrollment\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"O\n\x12\x43reateUserResponse\x12\x18\n\x10registrationCode\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\">\n\x13RegisterUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x18\n\x10registrationCode\x18\x02 \x01(\t\"[\n\x14RegisterUserResponse\x12\x11\n\tauthToken\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"]\n\x11PublicKeyResponse\x12\x1a\n\x12\x64ilithiumPublicKey\x18\x01 \x01(\x0c\x12\x14\n\x0ckeyAlgorithm\x18\x02 \x01(\t\x12\x16\n\x0ekeyGeneratedAt\x18\x03 \x01(\x03\"1\n\x0eSignedResponse\x12\x0c\n\x04\x62ody\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"7\n\x11\x41\x64minLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"L\n\x12\x41\x64minLoginResponse\x12\x12\n\nadminToken\x18\x01 \x01(\t\x12\x11\n\tadminName\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x42\x36\n#online.eracodes.protobuf.enrollmentB\x0f\x45nrollmentProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'enrollmentProto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#online.eracodes.protobuf.enrollmentB\017EnrollmentProto'
  _globals['_CREATEUSERREQUEST']._serialized_start=53
  _globals['_CREATEUSERREQUEST']._serialized_end=101
  _globals['_CREATEUSERRESPONSE']._serialized_start=103
  _globals['_CREATEUSERRESPONSE']._serialized_end=182
  _globals['_REGISTERUSERREQUEST']._serialized_start=184
  _globals['_REGISTERUSERREQUEST']._serialized_end=246
  _globals['_REGISTERUSERRESPONSE']._serialized_start=248
  _globals['_REGISTERUSERRESPONSE']._serialized_end=339
  _globals['_PUBLICKEYRESPONSE']._serialized_start=341
  _globals['_PUBLICKEYRESPONSE']._serialized_end=434
  _globals['_SIGNEDRESPONSE']._serialized_start=436
  _globals['_SIGNEDRESPONSE']._serialized_end=485
  _globals['_ADMINLOGINREQUEST']._serialized_start=487
  _globals['_ADMINLOGINREQUEST']._serialized_end=542
  _globals['_ADMINLOGINRESPONSE']._serialized_start=544
  _globals['_ADMINLOGINRESPONSE']._serialized_end=620
# @@protoc_insertion_point(module_scope)