# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: errorResponse.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'errorResponse.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x65rrorResponse.proto\"x\n\rErrorResponse\x12\x10\n\x08\x65rror_id\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x0c\n\x04path\x18\x06 \x01(\t*\xad\x02\n\tErrorCode\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x13\n\x0fINVALID_REQUEST\x10\x01\x12\x14\n\x10VALIDATION_ERROR\x10\x02\x12\x19\n\x15\x41UTHENTICATION_FAILED\x10\x03\x12\x18\n\x14\x41UTHORIZATION_FAILED\x10\x04\x12\x1d\n\x19REGISTRATION_CODE_INVALID\x10\x05\x12\x1d\n\x19REGISTRATION_CODE_EXPIRED\x10\x06\x12\x12\n\x0eUSER_NOT_FOUND\x10\x07\x12\x13\n\x0f\x44UPLICATE_EMAIL\x10\x08\x12\x17\n\x13\x43RYPTOGRAPHIC_ERROR\x10\t\x12\x12\n\x0e\x44\x41TABASE_ERROR\x10\n\x12\x19\n\x15INTERNAL_SERVER_ERROR\x10\x0b\x42,\n\x1eonline.eracodes.protobuf.errorB\nErrorProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'errorResponse_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036online.eracodes.protobuf.errorB\nErrorProto'
  _globals['_ERRORCODE']._serialized_start=146
  _globals['_ERRORCODE']._serialized_end=447
  _globals['_ERRORRESPONSE']._serialized_start=23
  _globals['_ERRORRESPONSE']._serialized_end=143
# @@protoc_insertion_point(module_scope)
